update abreviations set dept='OR' where name_eu='Arte eta Teknologia Esparrua 1';
update abreviations set dept='OR' where name_eu='Arte eta Teknologia Esparrua 2';
update abreviations set dept='OR' where name_eu='Arte eta Teknologia Esparrua 3';
update abreviations set dept='OR' where name_eu='Arte eta Teknologia Esparrua 4';
update abreviations set dept='GGZZ' where name_eu='Artearen Historia';
update abreviations set dept='ALE' where name_eu='Atzerriko Bigarren Hizkuntza I: Alemana';
update abreviations set dept='FRA' where name_eu='Atzerriko Bigarren Hizkuntza I: Frantsesa';
update abreviations set dept='ALE' where name_eu='Atzerriko Bigarren Hizkuntza: Alemana BH1';
update abreviations set dept='ALE' where name_eu='Atzerriko Bigarren Hizkuntza: Alemana BH2';
update abreviations set dept='ALE' where name_eu='Atzerriko Bigarren Hizkuntza: Alemana BH3';
update abreviations set dept='ALE' where name_eu='Atzerriko Bigarren Hizkuntza: Alemana BH4';
update abreviations set dept='FRA' where name_eu='Atzerriko Bigarren Hizkuntza: Frantsesa BH1';
update abreviations set dept='FRA' where name_eu='Atzerriko Bigarren Hizkuntza: Frantsesa BH2';
update abreviations set dept='FRA' where name_eu='Atzerriko Bigarren Hizkuntza: Frantsesa BH3';
update abreviations set dept='FRA' where name_eu='Atzerriko Bigarren Hizkuntza: Frantsesa BH4';
update abreviations set dept='ING' where name_eu='Atzerriko Bigarren Hizkuntza: Ingelesa BH2';
update abreviations set dept='ING' where name_eu='Atzerriko Hizkuntza I: Ingelesa';
update abreviations set dept='ING' where name_eu='Atzerriko Hizkuntza II: Ingelesa';
update abreviations set dept='FRA' where name_eu='Atzerriko Hizkuntza: Frantsesa BH2';
update abreviations set dept='ING' where name_eu='Atzerriko Hizkuntza: Ingelesa  3DC';
update abreviations set dept='ING' where name_eu='Atzerriko Hizkuntza: Ingelesa 4DC';
update abreviations set dept='ING' where name_eu='Atzerriko Hizkuntza: Ingelesa BH1';
update abreviations set dept='ING' where name_eu='Atzerriko Hizkuntza: Ingelesa BH2';
update abreviations set dept='ING' where name_eu='Atzerriko Hizkuntza: Ingelesa BH3';
update abreviations set dept='ING' where name_eu='Atzerriko Hizkuntza: Ingelesa BH4';
update abreviations set dept='OR' where name_eu='Autonomi eta Garapen Pertsonala 1';
update abreviations set dept='OR' where name_eu='Autonomi eta Garapen Pertsonala 2';
update abreviations set dept='OR' where name_eu='Autonomi eta Garapen Pertsonala 3';
update abreviations set dept='OR' where name_eu='Autonomi eta Garapen Pertsonala 4';
update abreviations set dept='ALE' where name_eu='Bigarre Atzerriko Hizkuntza II: Alemana';
update abreviations set dept='FRA' where name_eu='Bigarre Atzerriko Hizkuntza II: Frantsesa';
update abreviations set dept='BIOGEO' where name_eu='Biologia';
update abreviations set dept='BIOGEO' where name_eu='Biologia eta Geologia';
update abreviations set dept='BIOGEO' where name_eu='Biologia eta Geologia BH4';
update abreviations set dept='EKO' where name_eu='Ekonomia';
update abreviations set dept='TEKNO' where name_eu='Elektroteknia';
update abreviations set dept='EKO' where name_eu='Enpresaren ekonomia';
update abreviations set dept='ERLIJIO' where name_eu='Erl3 DC';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa (1.)';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa 1';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa 2';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa 3';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa 4DC';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa BH1';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa BH2';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa BH3';
update abreviations set dept='ERLIJIO' where name_eu='Erlijioa BH4';
update abreviations set dept='FILO' where name_eu='Erlijioen historia eta kultura BH1';
update abreviations set dept='FILO' where name_eu='Erlijioen historia eta kultura BH2';
update abreviations set dept='FILO' where name_eu='Erlijioen historia eta kultura BH3';
update abreviations set dept='FILO' where name_eu='Erlijioen historia eta kultura BH4';
update abreviations set dept='GGZZ' where name_eu='Esp. H.';
update abreviations set dept='OR' where name_eu='Esparru Praktikoa';
update abreviations set dept='OR' where name_eu='Esparru Zientifiko-Matematikoa';
update abreviations set dept='OR' where name_eu='Esparru zientifiko-matematikoa 3DC';
update abreviations set dept='OR' where name_eu='Esparru zientifiko-matematikoa 4DC';
update abreviations set dept='EUSK' where name_eu='Euskal Hizkuntza eta Literatura BH1';
update abreviations set dept='EUSK' where name_eu='Euskal Hizkuntza eta Literatura BH2';
update abreviations set dept='EUSK' where name_eu='Euskal Hizkuntza eta Literatura BH3';
update abreviations set dept='EUSK' where name_eu='Euskal Hizkuntza eta Literatura BH4';
update abreviations set dept='EUSK' where name_eu='Euskal Hizkuntza eta Literatura I';
update abreviations set dept='EUSK' where name_eu='Euskal Hizkuntza eta Literatura II';
update abreviations set dept='FILO' where name_eu='Filosofia eta herritartarsuna';
update abreviations set dept='FILO' where name_eu='Filosofiaren Historia';
update abreviations set dept='FK' where name_eu='Fisika';
update abreviations set dept='FK' where name_eu='Fisika eta Kimika';
update abreviations set dept='FK' where name_eu='Fisika eta Kimika BH4';
update abreviations set dept='FK' where name_eu='Fisika eta Kimika Sakontzen BH4';
update abreviations set dept='GAZTE' where name_eu='Gaztelania eta Literatura BH1';
update abreviations set dept='GAZTE' where name_eu='Gaztelania eta Literatura BH2';
update abreviations set dept='GAZTE' where name_eu='Gaztelania eta Literatura BH3';
update abreviations set dept='GAZTE' where name_eu='Gaztelania eta Literatura BH4';
update abreviations set dept='GAZTE' where name_eu='Gaztelania eta Literatura I';
update abreviations set dept='GAZTE' where name_eu='Gaztelania eta Literatura II';
update abreviations set dept='GGZZ' where name_eu='Geografia';
update abreviations set dept='OR' where name_eu='Gizarte Autonomi eta Elkarreragina 1';
update abreviations set dept='OR' where name_eu='Gizarte Autonomi eta Elkarreragina 2';
update abreviations set dept='OR' where name_eu='Gizarte Autonomi eta Elkarreragina 3';
update abreviations set dept='OR' where name_eu='Gizarte Autonomi eta Elkarreragina 4';
update abreviations set dept='OR' where name_eu='Gizarte eta hizkuntza esparrua';
update abreviations set dept='OR' where name_eu='Gizarte eta Natura esparrua 1';
update abreviations set dept='OR' where name_eu='Gizarte eta Natura esparrua 2';
update abreviations set dept='OR' where name_eu='Gizarte eta Natura esparrua 3';
update abreviations set dept='OR' where name_eu='Gizarte eta Natura esparrua 4';
update abreviations set dept='GGZZ' where name_eu='Gizarte Zientziak, Geografia eta Historia BH1';
update abreviations set dept='GGZZ' where name_eu='Gizarte Zientziak, Geografia eta Historia BH2';
update abreviations set dept='GGZZ' where name_eu='Gizarte Zientziak, Geografia eta Historia BH3';
update abreviations set dept='GGZZ' where name_eu='Gizarte Zientziak, Geografia eta Historia BH4';
update abreviations set dept='GH' where name_eu='Gorputz Hezkuntza';
update abreviations set dept='GH' where name_eu='Gorputz Hezkuntza 3DC';
update abreviations set dept='GH' where name_eu='Gorputz Hezkuntza 4DC';
update abreviations set dept='GH' where name_eu='Gorputz Hezkuntza BH1';
update abreviations set dept='GH' where name_eu='Gorputz Hezkuntza BH2';
update abreviations set dept='GH' where name_eu='Gorputz Hezkuntza BH3';
update abreviations set dept='GH' where name_eu='Gorputz Hezkuntza BH4';
update abreviations set dept='KLAS' where name_eu='Grekoa I';
update abreviations set dept='KLAS' where name_eu='Grekoa II';
update abreviations set dept='MATE' where name_eu='GZei aplikatutako Matematika I';
update abreviations set dept='MATE' where name_eu='GZei aplikatutako Matematika II';
update abreviations set dept='FILO' where name_eu='Herritartasunerako eta giza eskubideetarako hezkuntza BH3';
update abreviations set dept='FILO' where name_eu='Herritasunerako eta giza eskubideetarako hezkuntza 3DC';
update abreviations set dept='FILO' where name_eu='Hezkuntza etiko-zibikoa 4DC';
update abreviations set dept='FILO' where name_eu='Hezkuntza etiko-zibikoa BH4';
update abreviations set dept='OR' where name_eu='Hizkuntzaren eta gizartearen esparrua  4DC';
update abreviations set dept='OR' where name_eu='Hizkuntzaren eta gizartearen esparrua 3DC';
update abreviations set dept='TEKNO' where name_eu='Industri Teknologia II';
update abreviations set dept='TEKNO' where name_eu='Informatika BH4';
update abreviations set dept='TEKNO' where name_eu='Informazioaren eta komunikazioaren teknologiak';
update abreviations set dept='FK' where name_eu='Kimika';
update abreviations set dept='OR' where name_eu='Komunikazio Esparrua 1';
update abreviations set dept='OR' where name_eu='Komunikazio Esparrua 2';
update abreviations set dept='OR' where name_eu='Komunikazio Esparrua 3';
update abreviations set dept='OR' where name_eu='Komunikazio Esparrua 4';
update abreviations set dept='KLAS' where name_eu='Kultura Klasikoa - A BH3';
update abreviations set dept='TEKNO' where name_eu='Lanbide hastapena: bizitza heldu eta aktibora igarotzea BH4 (Opt)';
update abreviations set dept='KLAS' where name_eu='Latina BH4';
update abreviations set dept='KLAS' where name_eu='Latina I';
update abreviations set dept='KLAS' where name_eu='Latina II';
update abreviations set dept='GAZTE' where name_eu='Literatura Unibertsala';
update abreviations set dept='GAZTE' where name_eu='Literatura Unibertsala (Opt)  BH4';
update abreviations set dept='OR' where name_eu='Logika eta Matematika Esparrua 1';
update abreviations set dept='OR' where name_eu='Logika eta Matematika Esparrua 2';
update abreviations set dept='OR' where name_eu='Logika eta Matematika Esparrua 3';
update abreviations set dept='OR' where name_eu='Logika eta Matematika Esparrua 4';
update abreviations set dept='BIOGEO' where name_eu='Lurraren eta Ingurumenaren Zientziak';
update abreviations set dept='PLAS' where name_eu='Marrazketa Teknikoa I';
update abreviations set dept='PLAS' where name_eu='Marrazketa Teknikoa II';
update abreviations set dept='MATE' where name_eu='Matematika A BH4';
update abreviations set dept='MATE' where name_eu='Matematika B BH4';
update abreviations set dept='MATE' where name_eu='Matematika BH1';
update abreviations set dept='MATE' where name_eu='Matematika BH2';
update abreviations set dept='MATE' where name_eu='Matematika ES3';
update abreviations set dept='MATE' where name_eu='Matematika I';
update abreviations set dept='MATE' where name_eu='Matematika II';
update abreviations set dept='MATE' where name_eu='Matematika sakontzen BH2';
update abreviations set dept='MATE' where name_eu='Matematikan Sakontzen BH4';
update abreviations set dept='GGZZ' where name_eu='Mundu Garaikidearen Historia';
update abreviations set dept='BIOGEO' where name_eu='Mundu garaikiderako zienztziak';
update abreviations set dept='MUS' where name_eu='Musika BH1';
update abreviations set dept='MUS' where name_eu='Musika BH3';
update abreviations set dept='MUS' where name_eu='Musika BH4';
update abreviations set dept='MUS' where name_eu='Musikaren Historia';
update abreviations set dept='GGZZ' where name_eu='Nafarroako Geografia eta Historia';
update abreviations set dept='GGZZ' where name_eu='Nafarroako Geografia eta historia';
update abreviations set dept='BIOGEO' where name_eu='Natur Zientziak BH1';
update abreviations set dept='BIOGEO' where name_eu='Natur Zientziak BH2';
update abreviations set dept='BIOGEO' where name_eu='Natur Zientziak BH3';
update abreviations set dept='TEKNO' where name_eu='O.C. Energi Berristagarriak DBH3';
update abreviations set dept='MATE' where name_eu='Oinarrizko Matematika BH1';
update abreviations set dept='PLAS' where name_eu='Plastika eta Ikus-hezkuntza BH2';
update abreviations set dept='PLAS' where name_eu='Plastika eta Ikus-hezkuntza BH3';
update abreviations set dept='PLAS' where name_eu='Plastika eta Ikus-hezkuntza BH4';
update abreviations set dept='OR' where name_eu='Psikomotrizitate esparrua 1';
update abreviations set dept='OR' where name_eu='Psikomotrizitate esparrua 2';
update abreviations set dept='OR' where name_eu='Psikomotrizitate esparrua 3';
update abreviations set dept='OR' where name_eu='Psikomotrizitate esparrua 4';
update abreviations set dept='TEKNO' where name_eu='Teknologia (Opt) BH4';
update abreviations set dept='TEKNO' where name_eu='Teknologia BH1';
update abreviations set dept='TEKNO' where name_eu='Teknologia BH2';
update abreviations set dept='TEKNO' where name_eu='Teknologia BH4';
update abreviations set dept='TEKNO' where name_eu='Teknologia industriala I';
update abreviations set dept='MUS' where name_eu='Musikaren historia';
update abreviations set dept='TEKNO' where name_eu='Informazioaren eta komunikazioaren teknologiak';
update abreviations set dept='GH' where name_eu='IA Jarduera fisikoak';
update abreviations set dept='TEKNO' where name_eu='Informazioaren eta Komunikazioaren Teknologiak I';
update abreviations set dept='PLAS' where name_eu='Marrazketa Artistikoa I';
update abreviations set dept='BIOGEO' where name_eu='Anatomia Aplikatua';
update abreviations set dept='FILO' where name_eu='Balio etikoak DBH1';
update abreviations set dept='FILO' where name_eu='Balio etikoak BH3';
update abreviations set dept='MATE' where name_eu='Irakaskuntza akademikoetara bideratutako matematika DBH3';
update abreviations set dept='FK' where name_eu='Fisika eta Kimika DBH3';
update abreviations set dept='BIOGEO' where name_eu='Biologia eta geologia DBH3';
update abreviations set dept='PLAS' where name_eu='Marrazketa Artistikoa II';
update abreviations set dept='FILO' where name_eu='Psikologia';
update abreviations set dept='EKO' where name_eu='Administrazioaren eta Kudeaketaren Oinarriak';
update abreviations set dept='TEKNO' where name_eu='Informazioaren eta Komunikazioaren Teknologiak II';
