update grades set subject='Atzerriko Hizkuntza I: Ingelesa' where subject='Atzerriko lehen hizkuntza ingelesa I';
update grades set subject='Filosofia eta herritartarsuna' where subject='Filosofia';
update grades set subject='Atzerriko Bigarren Hizkuntza I: Alemana' where subject='Atzerriko Bigarren Hizkuntza Alemana I';
update grades set subject='Atzerriko Bigarren Hizkuntza I: Frantsesa' where subject='Atzerriko Bigarren Hizkuntza Frantsesa I';
update grades set subject='GZei aplikatutako Matematika I' where subject='Gizarte Zientziei Aplikatutako Matematika I';
update grades set subject='Musikaren Historia' where subject='ID Musikaren historia';
update grades set subject='Matematika BH1' where subject='Matematika DBH1';
update grades set subject='Musika BH1' where subject='Musika DBH1';
update grades set subject='Teknologia BH1' where subject='Teknologia DBH1';
update grades set subject='Erlijioa BH1' where subject='Erlijioa DBH1';
update grades set subject='Gorputz Hezkuntza BH1' where subject='Gorputz HezkuntzaDBH1';
update grades set subject='Euskal Hizkuntza eta Literatura BH1' where subject='Euskal hizkuntza eta literatura DBH1';
update grades set subject='Atzerriko Hizkuntza: Ingelesa BH1' where subject='Atzerriko lehen hizkuntza ingelesa DBH1';
update grades set subject='Natur Zientziak BH1' where subject='Biologia eta geologia DBH1';
update grades set subject='Gizarte Zientziak, Geografia eta Historia BH1' where subject='Geografia eta historia DBH1';
update grades set subject='Atzerriko Bigarren Hizkuntza: Frantsesa BH1' where subject='Atzerriko bigarren hizkuntza frantsesa DBH1';
update grades set subject='Atzerriko Bigarren Hizkuntza: Alemana BH1' where subject='Atzerriko bigarren hizkuntza alemana DBH1';
update grades set subject='Oinarrizko Matematika BH1' where subject='ID Oinarrizko Matematika BH1';
update grades set subject='Gorputz Hezkuntza BH3' where subject='Gorputz Hezkuntza DBH3';
update grades set subject='Atzerriko Bigarren Hizkuntza: Alemana BH3' where subject='Atzerriko bigarren hizkuntza alemana DBH3';
update grades set subject='Musika BH3' where subject='Musika DBH3';
update grades set subject='Atzerriko Hizkuntza: Ingelesa BH3' where subject='Atzerriko lehen hizkuntza ingelesa DBH3';
update grades set subject='Gizarte Zientziak, Geografia eta Historia BH3' where subject='Geografia eta historia DBH3';
update grades set subject='Atzerriko Bigarren Hizkuntza: Frantsesa BH3' where subject='Atzerriko bigarren hizkuntza frantsesa DBH3';
update grades set subject='Euskal Hizkuntza eta Literatura BH3' where subject='Euskal hizkuntza eta literatura DBH3';
update grades set subject='Erlijioa BH3' where subject='Erlijioa DBH3';
update grades set subject='Plastika eta Ikus-hezkuntza BH3' where subject='Plastika, ikus eta ikus-entzunezko hezikuntza DBH3';
update grades set subject='O.C. Energi Berristagarriak DBH3' where subject='ID Energia berriztagarriak BH3';
update grades set subject='Kultura Klasikoa - A BH3' where subject='Kultura klasikoa DBH3';
update grades set subject='Kultura Klasikoa - A BH3' where subject='Kultura klasikoa BH3';
update grades set subject='Gizarte Zientziak, Geografia eta Historia BH1' where subject='Geografia eta Historia DBH1';
update grades set subject='Atzerriko Bigarren Hizkuntza: Alemana BH1' where subject='Atzerriko bigarren hizkuntza alemana BH1';
update grades set subject='Atzerriko Hizkuntza: Ingelesa BH1' where subject='Atzerriko lehen hizkuntza ingelesa BH1';
update grades set subject='Gorputz Hezkuntza BH1' where subject='Gorputz hezkuntza BH1';
update grades set subject='Natur Zientziak BH1' where subject='Biologia eta Geologia BH1';
update grades set subject='Euskal Hizkuntza eta Literatura BH1' where subject='Euskal hizkuntza eta Literatura DBH1';
update grades set subject='Atzerriko Bigarren Hizkuntza: Frantsesa BH1' where subject='Atzerriko bigarren hizkuntza frantsesa BH1';
update grades set subject='Plastika eta Ikus-hezkuntza BH3' where subject='Plastika, ikus eta ikus-entzunezko hezikuntza BH3';
update grades set subject='Atzerriko Hizkuntza: Ingelesa BH3' where subject='Atzerriko lehen hizkuntza ingelesa BH3';
update grades set subject='Euskal Hizkuntza eta Literatura BH3' where subject='Euskal hizkuntza eta Literatura BH3';
update grades set subject='Gizarte Zientziak, Geografia eta Historia BH3' where subject='Geografia eta Historia BH3';
update grades set subject='Atzerriko Bigarren Hizkuntza: Frantsesa BH3' where subject='Atzerriko bigarren hizkuntza frantsesa BH3';
update grades set subject='Atzerriko Bigarren Hizkuntza: Alemana BH3' where subject='Atzerriko bigarren hizkuntza alemana BH3';
update grades set subject='Teknologia Industriala I' where subject='Teknologia industriala I';
update grades set subject='Atzerriko Hizkuntza II: Ingelesa' where subject='Atzerriko lehen hizkuntza ingelesa II';
update grades set subject='Bigarren Atzerriko Hizkuntza II: Alemana' where subject='Atzerriko Bigarren Hizkuntza Alemana II';
update grades set subject='Bigarren Atzerriko Hizkuntza II: Frantsesa' where subject='Atzerriko Bigarren Hizkuntza Frantsesa II';
update grades set subject='Enpresaren ekonomia' where subject='Enpresaren Ekonomia';
update grades set subject='Esp. H.' where subject='Espainiako Historia';
update grades set subject='GZei aplikatutako Matematika II' where subject='Gizarte Zientziei Aplikatutako Matematika II';
update grades set subject='ID Jarduera fisikoak eta osasuna' where subject='IA Jarduera fisikoak';
update grades set subject='Industri Teknologia II' where subject='Teknologia Industriala II';
update grades set subject='Atzerriko Bigarren Hizkuntza: Alemana BH2' where subject='Atzerriko bigarren hizkuntza alemana BH2';
update grades set subject='Atzerriko Bigarren Hizkuntza: Frantsesa BH2' where subject='Atzerriko bigarren hizkuntza frantsesa BH2';
update grades set subject='Atzerriko Hizkuntza: Ingelesa BH2' where subject='Atzerriko lehen hizkuntza ingelesa BH2';
update grades set subject='Euskal Hizkuntza eta Literatura BH2' where subject='Euskal hizkuntza eta Literatura BH2';
update grades set subject='Gizarte Zientziak, Geografia eta Historia BH2' where subject='Geografia eta Historia BH2';
update grades set subject='Gorputz Hezkuntza BH2' where subject='Gorputz hezkuntza BH2';
update grades set subject='Plastika eta Ikus-hezkuntza BH2' where subject='Plastika, ikus eta ikus-entzunezko hezkuntza BH2';
update grades set subject='Atzerriko Bigarren Hizkuntza: Alemana BH4' where subject='Atzerriko bigarren hizkuntza alemana BH4';
update grades set subject='Atzerriko Bigarren Hizkuntza: Frantsesa BH4' where subject='Atzerriko bigarren hizkuntza frantsesa BH4';
update grades set subject='Atzerriko Hizkuntza: Ingelesa BH4' where subject='Atzerriko lehen hizkuntza ingelesa BH4';
update grades set subject='Euskal Hizkuntza eta Literatura BH4' where subject='Euskal hizkuntza eta Literatura BH4';
update grades set subject='Gizarte Zientziak, Geografia eta Historia BH4' where subject='Geografia eta Historia BH4';
update grades set subject='Gorputz Hezkuntza BH4' where subject='Gorputz hezkuntza BH4';
update grades set subject='Plastika eta Ikus-hezkuntza BH4' where subject='ID Adierazpen artistikoko tailerra BH4';
update grades set subject='Informatika BH4' where subject='Informazioaren eta komunikazioaren teknologiak BH4';
update grades set subject='Matematika B BH4' where subject='Irakaskuntza akademikoetara bideratutako matematika BH4';
update grades set subject='Matematika A BH4' where subject='Irakaskuntza aplikatuetara bideratutako matematika BH4';
update grades set subject='Plastika eta Ikus-hezkuntza BH4' where subject='Plastika, ikus eta ikus-entzunezko hezikuntza BH4';
